### ISSUE TITLE
Demo online and ScreenCast

### ISSUE THREAD

**Issue by Level0r0s** [apHarmony/jsharmony#1]
Hello. Are there any screencasts about jsHarmony? and some online demo ??
Tanks

Cristiano

**Comment by palczewski** [comment]
Cristiano - that's a great idea - we'll create some screencasts of how to get started with jsHarmony.  We are working on a major version release in the next month, so after that's done, we'll also have a great set of tutorials.  I'll keep you updated when it's ready.

**Comment by Level0r0s** [comment]
Could you pass some link from an application running with jsHarmony? Is it already being used in production?

**Comment by palczewski** [comment]
Cristiano, our company has used jsHarmony for several production applications, however they are back-end systems for companies, so they are not publicly accessible.  We have a issue tracking system we'll set up as a public demo.
