### ISSUE TITLE
internationalization User Interface

### ISSUE THREAD

**Issue by fabiograz** [apHarmony/jsharmony#17]
Hi,
how can I translate the user interface in other languages? How can I set the user interface language based on user preference?
Can I contribute to translate the framework to Italian language?

Thanks.
Fabio.

**Comment by palczewski** [comment]
Hi Fabio,
The field names, templates, and system error messages are user-defined and can be overridden, so if you want to target a specific language, you could name the fields as needed.
If you are looking for the capability to change User Interface based on preference, it's certainly doable, however there would be some development work involved.
If someone is interested in either developing that component, or sponsoring development, please let me know and I'll be happy to put together specs.
